import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { ClerkProvider } from "@clerk/nextjs"
import { syncUser } from "@/action/user.action";
import { currentUser } from "@clerk/nextjs/server";
import { Toaster } from "react-hot-toast"

const geistSans = Geist({
	variable: "--font-geist-sans",
	subsets: ["latin"],
});

const geistMono = Geist_Mono({
	variable: "--font-geist-mono",
	subsets: ["latin"],
});

export const metadata: Metadata = {
	title: "Apotek Pelangi",
	description: "Generated by create next app",
};

export default async function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	const user = await currentUser()

	if (user) await syncUser()

	return (
		<ClerkProvider>
			<html lang="id" suppressHydrationWarning>
				<body
					className={`${geistSans.variable} ${geistMono.variable} antialiased`}
				>
					<main className="min-h-[calc(100vh-10rem)]">
						{children}
					</main>
					<Toaster />
				</body>
			</html>
		</ClerkProvider>
	);
}