import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";
import { ClerkProvider } from "@clerk/nextjs"
import { syncUser } from "@/action/user.action";

const geistSans = Geist({
	variable: "--font-geist-sans",
	subsets: ["latin"],
});

const geistMono = Geist_Mono({
	variable: "--font-geist-mono",
	subsets: ["latin"],
});

export const metadata: Metadata = {
	title: "Apotek Pelangi",
	description: "Generated by create next app",
};

export default async function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	try {
		await syncUser()
	} catch (e) {
		console.error(`Gagal menyinkronkan data user.`)
	}

	return (
		<ClerkProvider>
			<html lang="id">
				<body
					className={`${geistSans.variable} ${geistMono.variable} antialiased`}
				>
					<Navbar />
					<main className="min-h-[calc(100vh-10rem)]">
						{children}
					</main>
					<Footer />
				</body>
			</html>
		</ClerkProvider>
	);
}
