import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { ClerkProvider } from "@clerk/nextjs"
import { syncUser } from "@/action/user.action";
import { currentUser } from "@clerk/nextjs/server";
import { Toaster } from "react-hot-toast"
import { idID } from "@clerk/localizations"

const geistSans = Geist({
	variable: "--font-geist-sans",
	subsets: ["latin"],
});

const geistMono = Geist_Mono({
	variable: "--font-geist-mono",
	subsets: ["latin"],
});

export const metadata: Metadata = {
	title: "Apotek Pelangi",
	description: "Generated by create next app",
};

export default async function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	const user = await currentUser()

	if (user) await syncUser()

	return (
		<ClerkProvider localization={idID}>
			<html lang="id" suppressHydrationWarning>
				<body
					className={`${geistSans.variable} ${geistMono.variable} antialiased`}
				>
					<main className="min-h-[calc(100vh-10rem)]">
						{children}
					</main>
					<Toaster
						toastOptions={{
							success: {
								duration: 3000,
								iconTheme: {
									primary: '#10B981',
									secondary: '#E2F9F3',
								},
								style: {
									background: '#E2F9F3',
									color: '#047857',     
									border: '1px solid #10B981',
									padding: '16px',
								},
							},
							error: {
								duration: 5000,
								iconTheme: {
									primary: '#EF4444',
									secondary: '#FEE2E2',
								},
								style: {
									background: '#FEE2E2',
									color: '#B91C1C',
									border: '1px solid #EF4444',
									padding: '16px',
								},
							},
						}}
					/>
				</body>
			</html>
		</ClerkProvider>
	);
}